FROM --platform=linux/amd64 bitnami/minideb

ENV DEBIAN_FRONTEND noninteractive

# Ejecutar todo con bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt update && \
    apt install -q -y telnet net-tools iputils-ping && \
    apt clean autoclean -y && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT sh
